### ISSUE TITLE
Error: Module.indexThere was no ModuleGraph assigned to the Module for backward-compat (Use the new API)

### ISSUE THREAD

**Issue by joker-777** [fqborges/webpack-fix-style-only-entries#56]
I'm seeing this error

```
Error: Module.indexThere was no ModuleGraph assigned to the Module for backward-compat (Use the new API)
    at /app/node_modules/webpack/lib/ModuleGraph.js:814:12
    at deprecated (node:internal/util:124:12)
    at Function.getModuleGraphForModule (/app/node_modules/webpack/lib/ModuleGraph.js:805:18)
    at NormalModule.get index [as index] (/app/node_modules/webpack/lib/Module.js:238:22)
    at collectEntryResources (/app/node_modules/webpack-fix-style-only-entries/index.js:62:20)
    at /app/node_modules/webpack-fix-style-only-entries/index.js:81:32
    at Array.forEach (<anonymous>)
    at collectEntryResources (/app/node_modules/webpack-fix-style-only-entries/index.js:75:25)
    at /app/node_modules/webpack-fix-style-only-entries/index.js:35:30
    at Hook.eval [as call] (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
```

I'm also seeing a couple of deprecation warnings in the beginning.

```
(node:410) [DEP_WEBPACK_CHUNK_HAS_ENTRY_MODULE] DeprecationWarning: Chunk.hasEntryModule: Use new ChunkGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:410) [DEP_WEBPACK_CHUNK_ENTRY_MODULE] DeprecationWarning: Chunk.entryModule: Use new ChunkGraph API
(node:410) [DEP_WEBPACK_MODULE_INDEX] DeprecationWarning: Module.index: Use new ModuleGraph API
```

**Comment by webdiscus** [comment]
Hallo @joker-777,

the readme says:

> ⚠️ The current package version is not compatible with webpack 5.\
There is a fork here that is compatible: [webpack-remove-empty-scripts](https://github.com/webdiscus/webpack-remove-empty-scripts)

**Comment by joker-777** [comment]
@webdiscus Thanks for letting me know. I missed this part in the readme.
